# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.clone("https://github.com/JuliaDiffEq/DifferentialEquations.jl")'
  - julia -e 'Pkg.clone("https://github.com/JuliaDiffEq/ParameterizedFunctions.jl")'
  - julia -e 'Pkg.clone("https://github.com/JuliaDiffEq/DiffEqProblemLibrary.jl")'
  - julia -e 'Pkg.checkout("DifferentialEquations")'
  - julia -e 'Pkg.checkout("AlgebraicDiffEq")'
  - julia -e 'Pkg.checkout("StochasticDiffEq")'
  - julia -e 'Pkg.checkout("FiniteElementDiffEq")'
  - julia -e 'Pkg.checkout("DiffEqDevTools")'
  - julia -e 'Pkg.checkout("DiffEqBase")'
  - julia -e 'Pkg.checkout("OrdinaryDiffEq")'
  - julia -e 'Pkg.checkout("DiffEqProblemLibrary")'
  - julia -e 'Pkg.checkout("StokesDiffEq")'
  - julia -e 'Pkg.checkout("DiffEqParamEstim")'
  - julia -e 'Pkg.add("Documenter")'
after_success:
  - julia -e 'cd(Pkg.dir("DiffEqDocs")); include(joinpath("docs", "make.jl"))'
