name = "DiffEqDocs"
uuid = "d91efeb5-c178-44a6-a2ee-51685df7c78e"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "7.20.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "1"
ExplicitImports = "1.14.0"
julia = "1.10"

[extras]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DifferentialEquations", "ExplicitImports", "Test"]
