[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
BVProblemLibrary = "ded0fc24-dfea-4565-b1d9-79c027d14d84"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DAEProblemLibrary = "dfb8ca35-80a1-48ba-a605-84916a45b4f8"
DASKR = "165a45c3-f624-5814-8e85-3bdf39a7becd"
DDEProblemLibrary = "f42792ee-6ffc-4e2a-ae83-8ee2f22de800"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiffEqDocs = "d91efeb5-c178-44a6-a2ee-51685df7c78e"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JumpProblemLibrary = "faf0f6d7-8cee-47cb-b27c-1eb80cef534e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ODEProblemLibrary = "fdc4e326-1af4-4b90-96e7-779fcce2daa5"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SDEProblemLibrary = "c72e72a9-a271-4b2b-8966-303ed956772e"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AlgebraicMultigrid = "0.5"
BSON = "0.3"
BenchmarkTools = "1"
BoundaryValueDiffEq = "2, 3"
BVProblemLibrary = "0.1.2"
CSV = "0.10"
DAEProblemLibrary = "0.1"
DASKR = "2.9.1"
DDEProblemLibrary = "0.1"
DataFrames = "1.4"
DiffEqBase = "6.106"
DiffEqCallbacks = "2.24"
DifferentialEquations = "7.6"
Distributions = "0.25"
Documenter = "0.27"
FiniteDiff = "2"
ForwardDiff = "0.10"
IncompleteLU = "0.2"
JLD2 = "0.4"
JumpProblemLibrary = "0.1"
ModelingToolkit = "8"
ODEProblemLibrary = "0.1"
Optimization = "3"
OptimizationNLopt = "0.1"
OrdinaryDiffEq = "6.31"
Plots = "1"
RecursiveArrayTools = "2"
SDEProblemLibrary = "0.1"
SciMLBase = "1.34"
StaticArrays = "1"
Sundials = "4.11.3"
Symbolics = "4, 5"
Unitful = "1"
